[Merge after #789 and #791] [jsk_rqt_plugins] Support SetBool for Service Buttons
jsk-ros-pkg/jsk_visualization pull request #792
Opened 2020-11-17 09:18 UTC by knorth55

merge after #780 and #791 

Support `SetBool` service for rqt_service_buttons`.

You can try with following command:

```bash
roslaunch jsk_rqt_plugins sample_service_buttons.launch
```

2020-11-17 11:54 UTC, iory approved these changes

2020-11-18 23:39 UTC, k-okada requested changes
please resolve conflicts

2020-11-21 14:50 UTC, knorth55 commented
@k-okada Travis passed, and I resolved the conflict. Can you merge this PR?

2020-11-22 10:24 UTC, merged

2020-12-14 07:56 UTC, Naoki-Hiraoka commented
@k-okada 

I use this!
I would appreciate it if you could release this.

![Screenshot from 2020-12-14 16-51-38](https://user-images.githubusercontent.com/32383525/102054419-b91b7680-3e2c-11eb-803f-3c2a7e166581.png)