Change pie chart color at your custom threshold
jsk-ros-pkg/jsk_visualization pull request #840
Opened 2021-11-25 03:08 UTC by shmpwk

[Pie chart] 
You can set the max color and med color at your custom max and med threshold after enabling `auto color change`.

e.x. 
1. `roslaunch jsk_rviz_plugins piechart_sample.launch`
2. Enable `auto color change` on rviz
3. Set max color (med color)
4. Set max threshold (med threshold)

https://user-images.githubusercontent.com/42209144/143372588-07feb002-7d5d-4d41-a48e-bef074767c5e.mp4

2021-11-25 06:24 UTC, OmerKonan approved these changes
It works perfect

2021-11-25 07:17 UTC, yt approved these changes

2021-11-26 13:38 UTC, k-okada requested changes
@shmpwk thank you, please update document too https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/doc/jsk_rviz_plugins/plugins/pie_chart.md

2021-11-29 02:25 UTC, k-okada approved these changes
thank you

2021-11-29 02:25 UTC, merged